### ISSUE TITLE
develop 최종 수정 사항

### ISSUE THREAD

**Issue by zoonyoung** [codeit-sprint4-team9/rolling-paper#149]
# TODO
- [ ] 메인 헤더 반응형 (1248px 이상에서 더이상 길이늘어나지 않아야함) 
- [ ]  카드 헤더 반응형(1248px 이상에서 더이상 길이늘어나지 않아야함) 
- [ ]  캐러셀 우측 살짝 보이는 css 변경
- [ ] 태블릿, 모바일 캐러셀 해제
- [ ] 최근에 만든 롤링페이퍼는 개수 10개정도로 줄이는게 어떨지?
- [ ] Toast위치변경
- [ ] EDIT에서 페이퍼 추가 박스 제거 
- [ ] 페이지 삭제하기 & 저장하기 UI가 직관적이지 않음.
  - 글지우는 거랑 페이지 지우는거랑 좀 헷갈림
  - 삭제하시겠습니까 창을 alert -> Modal 고려
- [ ] 롤링페이퍼 생성 페이지 백그라운드 이미지 서버에 있는 URL로 변경
- [ ] Data Fetching 과정에 보여줄 스켈렌톤 혹은 Loading 스피너 고려
- [ ] 데이터를 못받아 오거나 & Error 발생시 사용자에게 어떻게 보여줄지 생각
